log_comet: true
comet:
  project_name: "GeoLife2022"
  tags: []


num_species: 17037


module:
  model: "resnet18"
  #fc: "linear"
  pretrained: true
  lr: 0.001
  
  
scheduler:
  name: "ReduceLROnPlateau" #"ReduceLROnPlateau" "StepLR" "WarmUp"
  reduce_lr_plateau: 
    factor: 0.5
    lr_schedule_patience: 5
  step_lr:
    step_size: 100
    gamma: 0.5
  warmup:
    warmup_epochs: 10
    max_epochs: 100


data:
  loaders:
    num_workers: 4
    batch_size: 8
  datatype: "img"   #refl or img 
  bands: ["rgb"] #, "nir"]
  splits:  # available options: [train, train+val, val, test]
    train: train  #  `val` for debugging purposes . should be train+val
    val: val
    test: test  

  transforms:
    - name: crop
      ignore: true
      p: 0.5
      center: true # disable randomness, crop around the image's center
      size: [256, 256]
      
    - name: resize
      ignore: false
      size: [224,224]
    - name: hflip
      ignore: "val"
      p: 0.5
    - name: vflip
      ignore: "val"
      p: 0.5
    - name: normalize
      ignore: True
      means: 
      std: 
      band: "rgb"
    

optimizer: "SGD" #"Adam"


#auto lr will only work if there is only one optimizer
auto_lr_find: True

