log_comet: true
comet:
  project_name: "GeoLife2022"
  experiment_name: "rgbNearIR_baseline"
  tags: []

max_epochs: 50 # null
gpus: 1
use_ffcv_loader: False   #you have to use ["rgb", "near_ir"] in the data.bands !!

task: "base"  # [base, multitask]

num_species: 17037


module:
  model: "resnet50"  #options: [resnet18, resnet50, seco_resnet18_1m, seco_resnet50_1m, seco_resnet18_100k, seco_resnet50_100k] 
  #fc: "linear"
  pretrained: true
  lr: 0.01 # best lr = 0.3311311214825908
  
  
scheduler:
  name: "ReduceLROnPlateau" #"ReduceLROnPlateau" "StepLR" "WarmUp" "CosineRestarts"
  reduce_lr_plateau: 
    factor: 0.5
    lr_schedule_patience: 5
  step_lr:
    step_size: 100
    gamma: 0.5
  warmup:
    warmup_epochs: 10
  cosine:
    t_0: 10
    t_mult: 1
    eta_min: 0.001
    last_epoch: -1
#       max_epochs: 100


data:
  loaders:
    num_workers: 4
    batch_size: 32
  datatype: "img"   #refl or img 
  bands:  ["rgb", "near_ir"]   # available options: ["rgb", "near_ir", "landcover", "altitude", "all"]
  splits:  # available options: [train, train+val, val, test]
    train: train  #  `val` for debugging purposes . should be train+val
    val: val
    test: test  
  transforms:
    - name: crop
      ignore: True
      p: 0.5
      center: true # disable randomness, crop around the image's center
      size: [256, 256]
    - name: resize
      ignore: False
      size: [224,224]
    - name: hflip
      ignore: "val"
      p: 0.5
    - name: vflip
      ignore: "val"
      p: 0.5    
    - name: normalize
      ignore: False
      means: [106.9413, 114.8733, 104.5285] 
      std: [51.0005, 44.8595, 43.2014] 
      band: "rgb"
    - name: normalize
      ignore: False
      means: [131.0458]
      std: [53.0884]
      band: "near_ir"
      
optimizer: "SGD" #"Adam"

nesterov: True
momentum: 0.9
dampening: 0.15


#auto lr will only work if there is only one optimizer
auto_lr_find: True

losses:
#scale attribute is just for plotting if the values are very small 

#   criterion: "CrossEntropy" #or MAE or MSE  (loss to choosefor optim )
#   ce:
#     ignore: False
#       #weights on the cross entropy
#     lambd_pres: 10
#     lambd_abs: 1
  metrics:
    - name: topk-error
      ignore: False
      k: 30
      scale: 1
#     - name: topk-accuracy
#       ignore: False
#       k: 30
#       scale: 1
