
# HYDRA CONFIG

#defaults:
#   - defaults

args:

  config_file: "debug.yaml"  #  options: [debug.yaml,
                                    #             cnn_baseline.yaml, cnn_baseline_meli.yaml 
                                    #             cnn_baseline_multi.yaml, multi_loc.yaml]
  load_ckpt : ""
  note: null # Note about this training for comet logging
  use_comet: True # use comet.ml to log experiment
  resume: False # Load latest ckpt
  tags: null
  dev: False # Run this script in development mode
  
  seed: 1337
#   save_path: "/home/mila/s/sara.ebrahim-elkafrawy/scratch/ecosystem_project/exps"
#   save_path: "/home/mila/t/tengmeli/scratch/ecosystem_project/exps"
  output_dir: output

  overwrite: False
