log_wandb: true
wandb:
  project_name: "rs-downstream"
  experiment_name: "mosaiks_two_layers_overfit_no_preprocess"
  mode: "online"
  tags: []

max_epochs: 30000000 # null
gpus: 1
use_ffcv_loader: False   #you have to use ["rgb", "near_ir"] in the data.bands !!

task: "mosaiks"  # options: [base, multitask, seco, feats, ssl, mosaiks]
freeze: False  # in the case of using the whole pre-trained network as feature extractor

num_species: 17037

loss: "CrossEntropy" # options: [CrossEntropy, PolyLoss]

mosaiks:
  model_name: "two_layers" # options["one_layer", "two_layers", "custom"]
  learnable: False
  conv_bias: False
  num_feats: 512
  patch_size: 3
  in_channels: 3
  pool_size: 256
  pool_stride: 256
  bias: 0.0
  
  
module:
  model: "resnet50"  #options: [vgg16, resnet18, resnet50, seco_resnet18_1m, seco_resnet50_1m, seco_resnet18_100k, seco_resnet50_100k] 
  #fc: "linear"
  multimodal: False
  pretrained: true
  lr: 0.1 # best lr = 0.3311311214825908
  
        
scheduler:
  name: "ReduceLROnPlateau" #"ReduceLROnPlateau" "StepLR" "WarmUp" "CosineRestarts"
  reduce_lr_plateau: 
    factor: 0.5
    lr_schedule_patience: 5
  step_lr:
    step_size: 100
    gamma: 0.5
  warmup:
    warmup_epochs: 10
  cosine:
    t_0: 10
    t_mult: 1
    eta_min: 0.001
    last_epoch: -1
#       max_epochs: 100


data:
  loaders:
    num_workers: 4
    batch_size: 32
  datatype: "img"   #refl or img 
  bands:  ["rgb"]   # available options: ["rgb", "near_ir", "landcover", "altitude", "all"]
  splits:  # available options: [train, train+val, val, test]
    train: train  #  `val` for debugging purposes . should be train+val
    val: val
    test: test  
  transforms:
    - name: crop
      ignore: True
      p: 0.5
      center: true # disable randomness, crop around the image's center
      size: [256, 256]
    - name: resize
      ignore: False
      size: [224,224]
    - name: hflip
      ignore: "val"
      p: 0.5
    - name: vflip
      ignore: "val"
      p: 0.5    
    - name: normalize
      ignore: False
      means: [106.9413, 114.8733, 104.5285] 
      std: [51.0005, 44.8595, 43.2014] 
      band: "rgb"
    - name: normalize
      ignore: True
      means: [131.0458]
      std: [53.0884]
      band: "near_ir"
    - name: normalize
      ignore: True
      means: [298.1693]
      std: [459.3285]
      band: "altitude"
    - name: normalize
      ignore: True
      means: [17.4200]
      std: [9.5173]
      band: "landcover"
      
optimizer: "SGD" #  options: ["Adam", "SGD"]

nesterov: True
momentum: 0.9
dampening: 0.15


#auto lr will only work if there is only one optimizer
auto_lr_find: True

losses:
#scale attribute is just for plotting if the values are very small 

#   criterion: "CrossEntropy" #or MAE or MSE  (loss to choosefor optim )
#   ce:
#     ignore: False
#       #weights on the cross entropy
#     lambd_pres: 10
#     lambd_abs: 1
  metrics:
    - name: topk-error
      ignore: False
      k: 30
      scale: 1
#     - name: topk-accuracy
#       ignore: False
#       k: 30
#       scale: 1
